service: ton-back-test
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  environment:
    COUNT_API: https://api.countapi.xyz

functions:
  addCount:
    handler: src/count.addCount
    events:
      - httpApi:
          path: /count
          method: get
  resumeCount:
    handler: src/count.resumeCount
    events:
      - httpApi:
          path: /resume
          method: get