service: ton-back-test
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1

functions:
  addCount:
    handler: src/addCount.handler
    events:
      - httpApi:
          path: /count
          method: get
  resumeCount:
    handler: src/resumeCount.handler
    events:
      - httpApi:
        path: /resume
        method: get